version: "3.9"

services:
  colloquial-currencies:
    image: rajivvishwa/colloquial-currencies:latest
    container_name: colloquial-currencies
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - config/config.env:/app/config/config.env
      - config/colloquial_denominations.yml:/app/config/colloquial_denominations.yml
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3