[project]
name = "colloquialcurrencies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "forex-python>=1.8",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "streamlit>=1.45"
]